### ISSUE TITLE
Works for larger item sets?

### ISSUE THREAD

**Issue by zetsumyoshu** [osu-crypto/MultipartyPSI#1]
I just wanted to make sure if the code works for the larger item sets. With these set of commands on a fresh Ubuntu 18.04 setup the example Frontend command is busy on some processes and returns abruptly on some other processes, ie. does not complete successfully.

Steps used to reproduce:

# 1. Setup

git clone https://github.com/osu-crypto/MultipartyPSI
sudo apt-get update
sudo apt-get install build-essential nasm cmake

cd MultipartyPSI/thirdparty
bash ./all_linux.get
cd ..

cmake .
make

# 2. Run with itemset 2^12 works in 11 secs

echo "./bin/frontend.exe -n 5 -t 2 -m 12 -p 0 & ./bin/frontend.exe -n 5 -t 2 -m 12 -p 1 & ./bin/frontend.exe -n 5 -t 2 -m 12 -p 2 & ./bin/frontend.exe -n 5 -t 2 -m 12 -p 3 & ./bin/frontend.exe -n 5 -t 2 -m 12 -p 4" > run.sh
time bash run.sh

> 9
> 9
> 9
> 9
> 9
> Client Idx: 0
> setSize: 4096
> offlineTime:  449 ms
> hashingTime:  7 ms
> getOPRFTime:  1096 ms
> ss2DirTime:  5522 ms
> ssRoundTime:  7 ms
> intersection:  0 ms
> onlineTime:  6632 ms
> Total time: 7.081 s
> ------------------
> =========avg==========
> Client Idx: 0
> numParty: 5  numCorrupted: 2  setSize: 4096  nTrials:1
> offlineTime:  449 ms
> hashingTime:  7 ms
> getOPRFTime:  1096 ms
> ssClientTime:  5522 ms
> ssLeaderTime:  7 ms
> intersection:  0 ms
> onlineTime:  6632 ms
> Total time: 7.081 s
> ------------------
> Client Idx: 1
> setSize: 4096
> offlineTime:  472 ms
> hashingTime:  7 ms
> getOPRFTime:  10273 ms
> ss2DirTime:  46 ms
> ssRoundTime:  4 ms
> intersection:  0 ms
> onlineTime:  10330 ms
> Total time: 10.802 s
> ------------------
> 
> Leader Idx: 4
> #Output Intersection: 3664
> #Expected Intersection: 3664
> setSize: 4096
> offlineTime:  466 ms
> hashingTime:  14 ms
> getOPRFTime:  18 ms
> ss2DirTime:  0 ms
> ssRoundTime:  10319 ms
> intersection:  0 ms
> onlineTime:  10351 ms
> Total time: 10.817 s
> ------------------
> =========avg==========
> Leader Idx: 4
> #Output Intersection: 3664
> #Expected Intersection: 3664
> numParty: 5  numCorrupted: 2  setSize: 4096  nTrials:1
> offlineTime:  466 ms
> hashingTime:  14 ms
> getOPRFTime:  18 ms
> ssClientTime:  0 ms
> ssLeaderTime:  10319 ms
> intersection:  0 ms
> onlineTime:  10351 ms
> Total time: 10.817 s
> ------------------
> 
> real	0m10.849s
> user	0m20.239s
> sys	0m13.523s

# 3. Run with itemset 2^13 works in 60 secs

echo "./bin/frontend.exe -n 5 -t 2 -m 13 -p 0 & ./bin/frontend.exe -n 5 -t 2 -m 13 -p 1 & ./bin/frontend.exe -n 5 -t 2 -m 13 -p 2 & ./bin/frontend.exe -n 5 -t 2 -m 13 -p 3 & ./bin/frontend.exe -n 5 -t 2 -m 13 -p 4" > run.sh
time bash run.sh

> 9
> 9
> 9
> 9
> 9
> Client Idx: 0
> setSize: 8192
> offlineTime:  474 ms
> hashingTime:  30 ms
> getOPRFTime:  10952 ms
> ss2DirTime:  47427 ms
> ssRoundTime:  9 ms
> intersection:  0 ms
> onlineTime:  58418 ms
> Total time: 58.892 s
> ------------------
> =========avg==========
> Client Idx: 0
> numParty: 5  numCorrupted: 2  setSize: 8192  nTrials:1
> offlineTime:  474 ms
> hashingTime:  30 ms
> getOPRFTime:  10952 ms
> ssClientTime:  47427 ms
> ssLeaderTime:  9 ms
> intersection:  0 ms
> onlineTime:  58418 ms
> Total time: 58.892 s
> ------------------
> Client Idx: 1
> setSize: 8192
> offlineTime:  466 ms
> hashingTime:  17 ms
> getOPRFTime:  58026 ms
> ss2DirTime:  402 ms
> ssRoundTime:  16 ms
> intersection:  0 ms
> onlineTime:  58461 ms
> Total time: 58.927 s
> ------------------
> 
> Leader Idx: 4
> #Output Intersection: 3664
> #Expected Intersection: 3664
> setSize: 8192
> offlineTime:  494 ms
> hashingTime:  18 ms
> getOPRFTime:  36 ms
> ss2DirTime:  0 ms
> ssRoundTime:  58409 ms
> intersection:  0 ms
> onlineTime:  58463 ms
> Total time: 58.957 s
> ------------------
> =========avg==========
> Leader Idx: 4
> #Output Intersection: 3664
> #Expected Intersection: 3664
> numParty: 5  numCorrupted: 2  setSize: 8192  nTrials:1
> offlineTime:  494 ms
> hashingTime:  18 ms
> getOPRFTime:  36 ms
> ssClientTime:  0 ms
> ssLeaderTime:  58409 ms
> intersection:  0 ms
> onlineTime:  58463 ms
> Total time: 58.957 s
> ------------------
> 
> real	0m58.976s
> user	1m45.432s
> sys	0m56.946s

# 4. Run with itemset 2^14 fails practically every time

echo "./bin/frontend.exe -n 5 -t 2 -m 14 -p 0 & ./bin/frontend.exe -n 5 -t 2 -m 14 -p 1 & ./bin/frontend.exe -n 5 -t 2 -m 14 -p 2 & ./bin/frontend.exe -n 5 -t 2 -m 14 -p 3 & ./bin/frontend.exe -n 5 -t 2 -m 14 -p 4" > run.sh
time bash run.sh

> 9
> 9
> 9
> 9
> 9

After a couple of minutes one of clients outputs the beginning:

Client Idx: 1
setSize: 16384
offlineTime:  478 ms
hashingTime:  34 ms
getOPRFTime:  168878 ms
ss2DirTime:  5763 ms
ssRoundTime:  32 ms
intersection:  0 ms
onlineTime:  174707 ms
Total time: 175.185 s
------------------

![image](https://user-images.githubusercontent.com/45737405/51538475-0d449880-1e5a-11e9-8370-aabdf6fd97b8.png)

Then one of the processes, the leader I suppose, just keeps calculating forever. 

![image](https://user-images.githubusercontent.com/45737405/51542006-e8a0ee80-1e62-11e9-9e28-3da6e41e9ee7.png)

# 5. Run with itemset larger than 2^14 not tested

Any insights, things to test differently? @nitrieu or others?

**Comment by nitrieu** [comment]
Sorry. I just see your question :( 2^14 works for me (see below)
![image](https://user-images.githubusercontent.com/16380791/81283503-9f51bf80-9011-11ea-880a-56021d0a8d6e.png)
