### ISSUE TITLE
Is there an SDK for python to call？

### ISSUE THREAD

**Issue by cow-123** [osu-crypto/MultipartyPSI#2]
Hello,

I find that currently use MultipartyPSI by only the way of running command lines. Is there an SDK for python to call some api to complete a psi job？
In addition，if I encapsulate an SDK, and the network communication need be handled by Python instead C++. Can you give me some suggestions?

Thank you!

**Comment by nitrieu** [comment]
Sorry for the late reply. You can replace your network communication at https://github.com/osu-crypto/MultipartyPSI/blob/implement/frontend/OtBinMain.cpp#L2343
