### ISSUE TITLE
multiparty set union 

### ISSUE THREAD

**Issue by heybrooo** [osu-crypto/MultipartyPSI#3]
Is there a implementation of privacy set union for two-party or multi-party?

**Comment by rosulek** [comment]
https://github.com/osu-crypto/PSU implements https://eprint.iacr.org/2019/776

brand new: https://github.com/gayathrigarimella/PSI-analytics implements https://eprint.iacr.org/2021/243

**Comment by heybrooo** [comment]
Thank you very much~
