### ISSUE TITLE
Whether to support the input and output of the  csv file format

### ISSUE THREAD

**Issue by heybrooo** [osu-crypto/MultipartyPSI#4]
Hello, can it support the input and output of the specified csv file when multi-party psi? And could you please provide some guidance if we want to support it? Thanks~

**Comment by nitrieu** [comment]
Hi, you can modify the code and import your input at https://github.com/osu-crypto/MultipartyPSI/blob/implement/frontend/OtBinMain.cpp#L2381. Similar to https://github.com/osu-crypto/MultipartyPSI/blob/implement/frontend/OtBinMain.cpp#L2304, you can print output to a file
