### ISSUE TITLE
Bug: coredump if length of inputs is less than 5

### ISSUE THREAD

**Issue by Shareong** [osu-crypto/MultipartyPSI#5]
This is caused by dividing by zero.

codes:

https://github.com/osu-crypto/MultipartyPSI/blob/44e965607b0d27416420d32cd09e6fcc34782c3a/libOPRF/Hashing/SimpleHasher1.cpp#L200

https://github.com/osu-crypto/MultipartyPSI/blob/44e965607b0d27416420d32cd09e6fcc34782c3a/libOPRF/Hashing/CuckooHasher1.cpp#L182

https://github.com/osu-crypto/MultipartyPSI/blob/44e965607b0d27416420d32cd09e6fcc34782c3a/libOPRF/Hashing/SimpleHasher1.cpp#L287

https://github.com/osu-crypto/MultipartyPSI/blob/44e965607b0d27416420d32cd09e6fcc34782c3a/libOPRF/Hashing/CuckooHasher1.cpp#L235

fix 
``` c++
  mBinCount[0] = std::max(mParams.mBinScaler[0] * n, 1);
  mBinCount[1] = std::max(mParams.mBinScaler[1] * n, 1);
```

**Comment by nitrieu** [comment]
thank you for pointing it out.
