### ISSUE TITLE
BtSocket.h:74:9: error: invalid use of template-name ‘boost::asio::strand’

### ISSUE THREAD

**Issue by L-coder148** [osu-crypto/MultipartyPSI#6]
Hi，
when I run make，it occurs the following problem.
![image](https://user-images.githubusercontent.com/75669641/138593154-aa1eb919-8aa8-4fb7-98f4-f9d428d2794b.png)
The boost version is 1.64.0.
![image](https://user-images.githubusercontent.com/75669641/138593195-0d2bb6d9-46f3-4b25-a50e-d70124ff1326.png)

**Comment by nitrieu** [comment]
Even your screenshot shows boost 1.64, it looks to me that you are using a newer version of boost (installed by default).
