### ISSUE TITLE
Build project meet error about boost

### ISSUE THREAD

**Issue by StarKirby1102** [osu-crypto/MultipartyPSI#9]
Hello! When I build the project in the step "cmake ." after bashing all_linux.get, the error occured:

```txt
-- Could NOT find Boost: missing: system thread (found /usr/local/lib/cmake/Boost-1.77.0/BoostConfig.cmake (found version "1.77.0"))
CMake Error at cryptoTools/CMakeLists.txt:74 (message):
  Failed to find boost at Need system thread


-- Configuring incomplete, errors occurred!
See also "/home/starkirby/MultipartyPSI/CMakeFiles/CMakeOutput.log".
```
But the terminal remind me that I have done the previous step successfully, how to solve that? Thanks.

**Comment by StarKirby1102** [comment]
> 

![image](https://user-images.githubusercontent.com/64449233/167281218-e6f3d0be-8c30-48cf-afd1-c48924018e90.png)
This is my "thirdparty/linux" folder.

**Comment by intochange** [comment]
Excuse me, has your problem been solved?
